version: '3.4'

services:
  postgres_db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password1234
      - POSTGRES_DB=nestpresso
    ports:
      - '5432:5432'
    # restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - coffeejs-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=aly@coffeejs.com
      - PGADMIN_DEFAULT_PASSWORD=password1234
    ports:
      - '5433:80'
    # restart: always
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - coffeejs-network

volumes:
  db-data:
  pgadmin:

networks:
  coffeejs-network:
    driver: bridge
# redis:
# kafka
# nginx
